services:

  postgres:
    image: postgres:14
    container_name: postgresyouthfp
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - /home/ubuntu/app/youthfp/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - afriyan-network

  pgbounceryouthfp:
    image: edoburu/pgbouncer
    container_name: pgbounceryouthfp
    restart: always
    environment:
      DB_HOST: postgresyouthfp
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${DB_NAME}
      AUTH_TYPE: scram-sha-256
      POOL_MODE: session
      MAX_CLIENT_CONN: 1000
      DEFAULT_POOL_SIZE: 25
      LISTEN_PORT: 6432
    #ports:
    #  - "6432:6432"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "127.0.0.1", "-p", "6432", "-U", "${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - afriyan-network
      - dokploy-network

  nginxyouthfp:
    image: nginx:latest
    container_name: nginxyouthfp
    restart: unless-stopped
    ports:
      - "8087:80"     # App Spring Boot
    volumes:
      - /home/ubuntu/app/youthfp/backend/nginx:/etc/nginx
    depends_on:
      - afriyan1
      - afriyan2
    networks:
      - afriyan-network
      - dokploy-network

  minioyouthfp:
    image: minio/minio:latest
    container_name: minioyouthfp
    restart: unless-stopped
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command:
      - server
      - /data
      - --console-address
      - ":9001"
    volumes:
      - /home/ubuntu/app/youthfp/backend/minio:/data
    networks:
      - afriyan-network
      - dokploy-network

  redisyouthfp:
    image: redis:7-alpine
    container_name: redisyouthfp
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - afriyan-network

  keycloakyouthfpdb:
    image: postgres:15
    container_name: keycloakyouthfpdb
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: kcpassword
    volumes:
      - /home/ubuntu/app/youthfp/keycloak:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - afriyan-network

  keycloakyouthfp:
    image: quay.io/keycloak/keycloak:26.0.0
    container_name: keycloakyouthfp
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloakyouthfpdb
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: kcpassword
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin123
      KC_HOSTNAME: keycloak.youthfp.cm
      KC_PROXY_HEADERS: xforwarded
      KC_HTTP_ENABLED: "true"
    depends_on:
      keycloakyouthfpdb:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/8080 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 15
      start_period: 90s
    restart: unless-stopped
    networks:
      - afriyan-network
      - dokploy-network


  afriyan1:
    container_name: afriyan1
    image: belinga/afriyan:0.0.1
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${DB_NAME}
      LMTACCOUNTSID: ${LMTACCOUNTSID}
      LMTAUTHTOKEN: ${LMTAUTHTOKEN}
      LMTSENDER: ${LMTSENDER}
      LMT_URL: ${LMT_URL}
      KEYCLOAK_URL: ${KEYCLOAK_URL}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      KEYCLOAK_USERNAME: ${KEYCLOAK_USERNAME}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      KEYCLOAK_ENABLED: ${KEYCLOAK_ENABLED}
      KEYCLOAK_USELECACYJWT: ${KEYCLOAK_USELECACYJWT}
      MINIO_URL: ${MINIO_URL}
      MINIO_FILE_URL: ${MINIO_FILE_URL}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      REDIS_URL: ${REDIS_URL}
      REDIS_PORD: ${REDIS_PORD}
    volumes:
      - /home/ubuntu/app/youthfp/backend/uploads:/uploads
      - /home/ubuntu/app/youthfp/backend/logs:/var/integration
      - /home/ubuntu/app/youthfp/backend/config/application.properties:/config/application.properties
    depends_on:
      pgbounceryouthfp:
        condition: service_healthy
    networks:
      - afriyan-network

  afriyan2:
    container_name: afriyan2
    image: belinga/afriyan:0.0.1
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${DB_NAME}
      LMTACCOUNTSID: ${LMTACCOUNTSID}
      LMTAUTHTOKEN: ${LMTAUTHTOKEN}
      LMTSENDER: ${LMTSENDER}
      LMT_URL: ${LMT_URL}
      KEYCLOAK_URL: ${KEYCLOAK_URL}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
      KEYCLOAK_USERNAME: ${KEYCLOAK_USERNAME}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      KEYCLOAK_ENABLED: ${KEYCLOAK_ENABLED}
      KEYCLOAK_USELECACYJWT: ${KEYCLOAK_USELECACYJWT}
      MINIO_URL: ${MINIO_URL}
      MINIO_FILE_URL: ${MINIO_FILE_URL}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      REDIS_URL: ${REDIS_URL}
      REDIS_PORD: ${REDIS_PORD}
    volumes:
      - /home/ubuntu/app/youthfp/backend/uploads:/uploads
      - /home/ubuntu/app/youthfp/backend/logs:/var/integration
      - /home/ubuntu/app/youthfp/backend/config/application.properties:/config/application.properties
    depends_on:
      pgbounceryouthfp:
        condition: service_healthy
    networks:
      - afriyan-network

    #prometheus:
    #  image: prom/prometheus:latest
    #  container_name: prometheus_youthfp
    #  restart: unless-stopped
    #  volumes:
    #    - prometheus_data:/etc/prometheus
    #ports:
    #  - "9090:9090"
    #  networks:
    #    - afriyan-network


    #grafana:
    #  image: grafana/grafana:latest
    #  container_name: grafana_youthfp
    #  restart: unless-stopped
    #ports:
    #  - "3001:3000"
  #  volumes:
  #    - grafana_data:/var/lib/grafana
  #  environment:
  #    - GF_SECURITY_ADMIN_USER=admin
  #    - GF_SECURITY_ADMIN_PASSWORD=admin123
  #  networks:
  #    - afriyan-network
  #  depends_on:
  #    - prometheus

networks:
  afriyan-network:
    driver: bridge
  dokploy-network:
    external: true

volumes:
  redis_data: