spring.datasource.url=jdbc:postgresql://www.youthfp.cm:5433/afriyan1
spring.datasource.username=afriyan
spring.datasource.password=@Friyan987
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
#validate
springdoc.swagger-ui.path=/swagger-ui-custom.html
spring.web.resources.static-locations=classpath:/static/,file:uploads/
file.upload-dir=uploads/
tlmt.accountSid=A04341D2-9B26-4F90-82D2-F5E7D5F5A233
lmt.authToken=NqNkNJUaxO2VAWzobeQLfP1npCHwJsgopLiTtdqWpP
lmt.sender=AfriYAN CMR
lmt.url=https://sms.lmtgroup.com/api/v1/pushes
##################################################################################


spring.mail.host=smtp.camoo.com
spring.mail.port=587
spring.mail.username=youthfp@youthfp.cm
spring.mail.password=@Lingot75
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

unfpaphoto=classpath:/images/unfpa.png
young=classpath:/images/logo192.png
#spring.main.allow-circular-references=true

server.port=8087