package org.ligot.afriyan.entities;

public enum Categorie {

    SANTE_SEXUELLE,PLANNING_FAMILLIAL, HYGENE_MENSTRUELLE, GROSSESSE_PRECOSE, VIH_IST, DROGUE_STUPEFIANT, VVG;

    //"VIOLENCE BASE SUR LE GENRE"

}
