package org.ligot.afriyan.entities;

public enum ParamTypeEnum {
    WHATSAPP, CALL, SMS,STATISTICS, FACEBOOK, TWEETER, YOUTUBE, LOCALISATION, COLOR_BODY_VITRINE, COLOR_HEADER_VITRINE
    , COLOR_NAVBAR_VITRINE, COLOR_BTN_VITRINE, COLOR_BTN_ELEARNING, COLOR_BODY_ELEARNING, COLOR_HEADER_ELEARNING, UNFPA_LINK,
    COLOR_NAVBAR_ELEARNING, COLOR_BODY_CLIENT, COLOR_HEADER_CLIENT, COLOR_NAVBAR_CLIENT, COLOR_BTN_CLIENT, ;
}
