package org.ligot.afriyan.init;

public enum RolesName {
    USER, VISITOR,ROOT,SUPERADMIN,
    ADMIN,GESTIONNAIRECENTRE,
    COMMUNITY_COMMITTEE, CCPR_COMMITTEE,
    LOCAL_AUTHORITY, MAIRE,
    TECHNICAL_SERVICES, NOS_PARTNER;
}
